# -*- coding: utf-8 -*-
"""mmaction2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n2QyVggVjRBmETPJNoFIfPFJyRawyL8_
"""

!pip install -U openmim
!mim install mmengine
!mim install mmcv
!mim install mmdet
!mim install mmpose

!git clone https://github.com/open-mmlab/mmaction2.git
!pip install -v -e ./mmaction2

!mim download mmaction2 --config tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb --dest .

"""This code downloads the model for a RGB-based video understanding model. We should change this to switch to a pose-based one."""

!python mmaction2/demo/demo.py tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb.py \
    tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb_20220906-2692d16c.pth \
    /content/mmaction2/demo/demo.mp4 mmaction2/tools/data/kinetics/label_map_k400.txt